image: node:18.12
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@15
    - npm install
    - npm run buildProd
  artifacts:
    paths:
      - public
  only:
    - master
    - pages
