image: node:14.17.6
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@12.2.4
    - npm install
    - npm run buildProd
  artifacts:
    paths:
      - public
  only:
    - master
    - pages
